version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5450:5432"
    environment:
      POSTGRES_USER: Ailen
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: library_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:
